- next.config.js
- package.json
- pnpm-lock.yaml
- src/app/(account)/join-us/StepTwo.tsx
- src/app/(account)/sign-in/page.tsx
- src/components/Button.tsx
- src/components/ControlledField.tsx
- src/components/Field.tsx
- src/components/UserButton.tsx
- src/middleware.ts
Hi there, I'm new to the uni and the club.
I found you are using `zod` to validate form so I installed `react-hook-form` to optimise the code which makes the code cleaner and easier to maintain.
`join-us` & `forgot-password` can also be optimised. (which is a huge work XD) In that way, `Form` will not need so many props to set and get state. If you want to do that, please feel free to tell me. I'll be happy to help!
cc @phoenixpereira @rishiad
> Optimise form with `react-hook-form`

- src/app/(account)/settings/page.tsx
- src/app/api/payment/route.ts
> fix: Membership setting doesn't change after payment

- README.md
- docs/clerk.md
- package.json
- pnpm-lock.yaml
- src/app/(account)/settings/page.tsx
- src/app/admin/MemberForm.tsx
- src/app/admin/page.tsx
- src/app/api/payment/route.ts
- src/components/Autocomplete.tsx
- src/components/UserButton.tsx
- src/db/index.ts
- src/db/queries.ts
- src/db/schema.ts
- src/middleware.ts
Add admin panel
- Add admin panel
- Update docs
- Resolves #56 
N/A
> feat: Add admin panel

- src/components/ImageCarousel.tsx
> fix(carousel-image): preload images

- src/components/ImageCarousel.tsx
> Production 2024-02-18_00

- src/app/(account)/signin/page.tsx
- src/components/Header.tsx
Reverts compsci-adl/website#65
> Revert "Revert "fix: Header buttons""

- docs/redis.md
- src/app/api/payment/route.ts
- src/server/verify-membership-payment.ts
> fix(payment): verify payment with `orderId`

- src/server/verify-membership-payment.ts
Use paymentId to determine if payment complete to fix the payment not getting saved properly..
- Use paymentId to determine if payment complete
N/A
N/A
> fix(payment): use paymentId to determine if payment complete

- src/app/(home)/page.tsx
- src/components/Button.tsx
Stylistic fixes and adding join us button at the end of the home page
- Add "join us" button at the bottom of the page where there is the second call-to-action
- Centre sponsors in mobile view, rather than it being pushed to the left
Any remaining issues with screen resizing and responsiveness can be fixed later, as outlined in #83
> Stylistic fixes and adding join button

- src/app/(account)/join/steps/StepTwo.tsx
- src/app/sponsors/page.tsx
Fix spelling and grammar
* "The club **are**" to "The club **is**"
* "**an** university" to "**a** university"
> chore: more spelling and grammar fixes

- src/app/(account)/forgot-password/page.tsx
- src/app/(account)/join/steps/StepOne.tsx
- src/app/(account)/signin/page.tsx
Adds button loading indication (grays out button and prevents clicking) so that button can't be spammed when a request is in progress.
Add button loading for forgot password, sign in and first sign up step.
Partially addresses #58
> feat: add button loading to indicate request in progress

- src/app/(account)/join/steps/StepFour.tsx
- src/app/(account)/join/steps/StepOne.tsx
- src/app/(account)/signin/page.tsx
> feat: refresh rsc after mutation

- src/components/Header/HeaderClient.tsx
- src/components/Header/HeaderMobileClient.tsx
- src/components/Header/components/Links.tsx
- src/components/Header/components/SignInJoin.tsx
During the header refactor, the mobile menu had a few bugs such as not having any login links.
- Join and sign in button now show in mobile menu when signed out
- Sign out link shows up when signed in
- Red notification icon only shows when signed in
> fix(header): mobile menu has correct links and behaviour

- src/app/contact/Form.tsx
- src/app/contact/Sponsorship.tsx
> fix(contact): minor fix for mobile style

- src/app/api/member/route.ts
- src/db/schema.ts
> refactor: use `unique` for `clerkId` to avoid duplicate user in db

- src/app/about/page.tsx
- src/app/api/member/route.ts
- src/data/committee-members.ts
- src/data/events.ts
- src/data/links.ts
- src/db/schema.ts
Update Instagram link and comment out latex workshop and quiz night.
- Update Instagram link
- Comment out latex workshop and quiz night.
N/A
N/A
> Production 2024-03-19_00

- package.json
- pnpm-lock.yaml
- src/app/events/Events.tsx
- src/data/events.ts
The event status doesn't update correctly from upcoming to past because the event dates were being parsed with the incorrect timezone (default UTC) and the event end time was calculated outside the component, preventing updates after the initial render.
- Updated the `getEventDate` function to correctly parse and convert event dates to the ACST timezone using `luxon`.
- The event filtering logic is replaced inside the Events component, ensuring these values are recalculated on each render.
- Added a comment in events.ts to specify that all event times are in ACST.
Fixes #177 
N/A
> fix: Set timezone for end time and dynamically calculate event end

- .github/workflows/production.yml
Use Github runner for production build.
Use Github runner ubuntu-latest rather than self-hosted arm64 runner for production build.
N/A
N/A
> build(ci): Use Github runner for production build

- .github/workflows/production.yml
- Dockerfile
- next.config.mjs
- package.json
Optimise build workflow and use Github runner to fix the server sometimes crashing during build requiring a full instance restart.
- Used Node 22 rather than Node 18
- No typescript/eslint error checking for production workflow (I kept it for `ci-dev-pr` workflow since it's useful)
- Used SWC minify
- Removed tsec --noEmit from the build command
- Added build caching
- Switched to Github amd64 runner using QEMU rather than self-hosted arm64 runner
N/A
N/A
> build(ci): Optimise build workflow and use Github runner

- .github/workflows/production.yml
Use Docker output type and tar.gz.
Use Docker output type and tar.gz.
N/A
N/A
> fix(ci): Use Docker output type and tar.gz

- Dockerfile
Revert to node 18 to fix admin panel not working.
Revert to node 18 in dockerfile.
N/A
N/A
> fix(ci): Revert to node 18 to fix admin panel not working

- src/components/Header/index.tsx
- tailwind.config.ts
To fix the issue when screen width is around 1300px and the header text will appear as two lines
Added a breakpoint for hamburger menu at 1300px
fix #173
N/A
> fix: prevent header text appear as two lines

- src/app/(account)/join/steps/StepFive.tsx
- src/app/(account)/join/steps/StepFour.tsx
- src/app/(account)/join/store.ts
- src/app/about/page.tsx
- src/components/Field.tsx
- src/components/Footer.tsx
Add Uni Code of Conduct and Club Constitution links to join flow and miscellaneous changes.
- Update copyright year to the current dynamically
- Refactor notification categories to use dynamic names
- Add Uni Code of Conduct and Club Constitution links to join us flow
- Add the link to Club Constitution in About page
Fixes #227 
This PR is merging to the **2025** branch, which will be a **temporary staging branch** for **upcoming PRs** that will be merged for **the start of 2025**.  This includes changing auth to Keycloak, updating db schema for notifications, email for member sign-up, and adding the uni's code of contact and our constitution to our join us page.
> feat: Add Uni Code of Conduct and Club Constitution links

- .gitignore
- docs/keycloak.md
- keycloak/docker-compose.yml
Improve Keycloak setup documentation and add Docker Compose configuration
- Improve Keycloak setup documentation
- Add example development Docker Compose configuration for Keycloak
N/A
N/A
> docs(keycloak): Improve Keycloak setup documentation

- src/auth.ts
Add trustHost option in NextAuth config.
Add trustHost option in NextAuth config.
N/A
N/A
> fix(auth): Add trustHost option in NextAuth config

- src/env.mjs
Make NEXT_PUBLIC_DRIVE_LINK temporarily optional in environment configuration.
Make NEXT_PUBLIC_DRIVE_LINK temporarily optional in environment configuration.
N/A
N/A
> fix(env): Make NEXT_PUBLIC_DRIVE_LINK temporarily optional

- package.json
Add postinstall script for git hook to automatically install pre-commit git hook when you run `pnpm install`.
Add postinstall script for git hook.
Fixes #257 
N/A
> chore: Add postinstall script for git hook

- src/app/(home)/UpcomingEventCard.tsx
- src/app/events/EventCard.tsx
This pull request includes changes to the `UpcomingEventCard` and `EventCard` components to improve navigation and user experience. The most important changes are the addition of links to upcoming events and the introduction of scroll markers for event cards.
Improvements to navigation:
* [`src/app/(home)/UpcomingEventCard.tsx`](diffhunk://#diff-b5eb29c424a2c44f932856ab2ad0f77c51ab64751e7d45ddf3d0fb85ef646c68R3-R10): Added a `Link` component around the event details to enable navigation to specific events based on their title and date. 
Enhancements to user experience:
* [`src/app/events/EventCard.tsx`](diffhunk://#diff-1d49e77c99df3cb7272ea708fb7aa8dc45a8d25bd12f22d453fbb8966b614965L17-R20): Introduced an `id` attribute to event cards to act as scroll markers, making it easier to …
> feat(home): Link to main event card by clicking upcoming cards

- src/app/(home)/page.tsx
- src/app/events/Events.tsx
- src/data/events.ts
- src/utils/format-date.ts
Use end time from `event.time` instead of `event.date.endTime`.
- Parse `startTime` and `endTime` from `event.time`
- Replace `CURRENT_DATE` with `CURRENT_TIME` to check both date and time
#298
Added `startTime` and `endTime` attributes in `Event` for easier parsing
> fix(events): use correct end time from event.time

- src/app/(home)/page.tsx
- tailwind.config.ts
Optimize the home page sponsor display on mobile devices by adjusting the layout for different screen widths.
| Before | After |
|--------|-------|
| ![before](https://github.com/user-attachments/assets/c5432720-09c6-4bdd-b951-d4e4069060d7) | ![after](https://github.com/user-attachments/assets/cf8f2afc-d1a2-43c7-a496-40d73c2168cc) |
1. Adding 'xs' breakpoint at 300px
2. Updated home page sponsor layout:
0–300px → flex
301–479px → grid with 2 columns
480px+ → flex
This allows sponsors to display in two columns on most mobile devices, improving readability.
N/A
Not sure if this looks nicer to you guys, feel free to suggest.
> feat(layout): Optimise sponsor display on mobile
