- src/app/(account)/join-us/page.tsx
- src/app/(account)/join-us/steps/StepOne.tsx
- src/app/(account)/sign-in/page.tsx
- src/components/Header.tsx
- src/components/UserButton.tsx
> Convert `a` to nextjs `link`

- src/app/(account)/forgot-password/page.tsx
- src/app/(account)/join-us/page.tsx
- src/app/(account)/sign-in/page.tsx
- src/app/(home)/page.tsx
- src/app/contact/Form.tsx
- src/app/contact/page.tsx
- src/app/layout.tsx
- src/app/not-found.tsx
- src/components/Footer.tsx
- src/components/Link.tsx
- src/components/Paragraph.tsx
- src/components/Title.tsx
Reuse page height and top padding in layout
- Reuse page height and top padding in layout
- Reuse `Title` component
- Refactored some styles
close #32
> Reuse page height and top padding in layout

- src/data/sponsors.ts
When renaming one of the files, it wasn't updated in the code.
> fix(sponsors): use correct file name

- src/components/Header.tsx
- src/constants/breakpoints.ts
Makes the mobile menu close as expected.
- Fixes mobile menu remaining open on window resize
- Fixes mobile menu not automatically closing when the link is clicked
Fixes #41 and #42. 
N/A
> fix(header): Mobile menu closes as expected

- src/app/(account)/settings/page.tsx
- src/app/admin/MemberForm.tsx
> fix(admin): Minor fix

- src/app/(home)/page.tsx
- src/app/about/page.tsx
- src/app/events/FridayNight.tsx
- src/app/events/Info.tsx
- src/app/events/page.tsx
- src/components/Title.tsx
- tailwind.config.ts
Change and fix up some styling to improve the overall user experience
- Change variable for screen width
- Fix inconsistent font weight on home page
- Fix some overflowing elements
- Consistent box heights
> fix: Improve styling for pages

- src/app/(account)/signin/page.tsx
- src/components/Header.tsx
> fix: Header buttons

- src/app/(account)/signin/page.tsx
- src/components/Header.tsx
Reverts compsci-adl/website#64
> Revert "fix: Header buttons"

- src/components/Header.tsx
- src/server/verify-membership-payment.ts
> fix(server): member `undefined` when verify payment

- src/app/(account)/signin/page.tsx
- src/components/Header.tsx
> Production 2024-02-18_01

- src/components/Header.tsx
> fix(header): revert revert

- src/app/(account)/signin/page.tsx
> fix(signin): header buttons doesn't change after signin

- docs/redis.md
- src/app/(account)/signin/page.tsx
- src/app/api/payment/route.ts
- src/server/verify-membership-payment.ts
> Production 2024-02-19_01

- src/app/admin/MemberForm.tsx
> fix(admin): update member payment checkbox properly

- src/app/(account)/join/steps/StepFour.tsx
- src/app/(account)/settings/Settings.tsx
- src/utils/format-date.ts
Improve wording of user settings and sign up sections.
> chore: Better wording for user settings and sign up

- src/app/(account)/settings/tabs/MembershipSettings.tsx
Add loading state for the "Pay Online" button.
> chore: add loading for pay online button

- src/app/contact/Form.tsx
- src/app/contact/Sponsorship.tsx
> Production 2024-02-20_04

- src/db/index.ts
- src/server/check-user-exists.ts
- src/server/verify-membership-payment.ts
Cache redundant query in settings and header to avoid 504
> fix: Cache redundant query in settings and header

- src/app/contact/Form.tsx
- src/app/contact/Sponsorship.tsx
- src/components/Header/HeaderMobileClient.tsx
- src/components/Header/components/SignInJoin.tsx
> Production 2024-02-23_00

- src/app/api/member/route.ts
> fix(api/member): check user existence before insert to database

- src/app/about/page.tsx
- src/data/committee-members.ts
Update committee members
- Major refactor for committee type
- Update committee members
N/A
N/A
> chore: Update committee members

- src/app/about/page.tsx
- src/app/api/member/route.ts
- src/data/committee-members.ts
- src/db/schema.ts
> Production 2024-03-15_00

- src/data/events.ts
- src/data/links.ts
Update Instagram link and comment out latex workshop and quiz night.
- Update Instagram link
- Comment out latex workshop and quiz night.
N/A
N/A
> chore: update Instagram link and comment out events

- src/app/events/Events.tsx
- src/data/events.ts
Add url support to events.
- Add url support to events
- Add url for industry night sign up
N/A
N/A
> feat: add url support to events

- pnpm-lock.yaml
- src/app/events/Events.tsx
- src/data/events.ts
Add url support to events and update dependencies.
- Add url support to events
- Add url for industry night sign up
- Updates `follow-redirects` from 1.15.5 to 1.15.6
N/A
N/A
> Production 2024-03-21_00

- src/data/sponsors.ts
> chore: Update sponsors

- src/app/events/Events.tsx
- src/data/events.ts
Add dates for the LaTeX workshop and pub crawl. The URL/link feature for events has also been updated.
> chore: update events

- src/data/committee-members.ts
Wanted to add last name to committee list.
Added last name
None
> chore: updated name on committee list to full name

- .github/workflows/ci-dev-pr.yml
Fix build step in workflow failing due to missing secrets in forks. 
Change event trigger from `pull_request` to `pull_request_target`.
Fixes #155 
N/A
> fix: Run actions in context of the base of the pull request 

- src/app/open-source/page.tsx
Add a more obvious button to the open source page
Added a button component on the opence source page
[https://github.com/compsci-adl/website/issues/163](https://github.com/compsci-adl/website/issues/163)
> feat: add a button on open source page linking to the signup form

- .github/workflows/production.yml
Reverts compsci-adl/website#183
> Revert "build(ci): Use Github runner for production build"

- .github/workflows/production.yml
Output tar file correctly.
Output tar file correctly in docker buildx step.
N/A
N/A
> fix(ci): Output tar file correctly

- Dockerfile
Use node 20 to fix admin panel issue.
Use node 20 to fix admin panel issue.
N/A
N/A
> fix(ci) Use node 20 to fix admin panel issue

- src/app/admin/MemberForm.tsx
- src/app/admin/PaginationControls.tsx
- src/app/admin/page.tsx
Add pagination to admin page to fix query timeout.
- Add pagination to admin page to fix query timeout.
- Add page links for page navigation.
N/A
N/A
> fix(db): Add pagination to admin page to fix query timeout

- .env.local.example
- .github/workflows/ci-dev-pr.yml
- .github/workflows/production.yml
- Dockerfile
- src/app/layout.tsx
- src/env.mjs
Add umami tracking script
- Add umami tracking script
N/A
N/A
> chore: Add umami tracking script

- src/app/open-source/ProjectCard.tsx
- src/data/projects.ts
Add MyTimetable website link to open source page.
- Add MyTimetable website link to open source page.
N/A
N/A
> feat(open-source): Add MyTimetable website link

- src/data/events.ts
Update event details for AGM
- Update event description for AGM.
- Remove committee nomination link for AGM.
N/A
N/A
> chore(events): Update event details for AGM

- src/app/contact/Contact.tsx
- src/data/links.ts
Added TikTok link to footer
Added TikTok link after Instagram link
N/A
N/A
> feat: Add tiktok link

- src/app/contact/Contact.tsx
- src/data/links.ts
Added Youtube link to contact page and footer
added link to link.ts and Contact.tsx
N/A
N/A
> feat: add CS Club YouTube channel link

- src/data/events.ts
Remove cocktail night ticket link.
Remove cocktail night ticket link.
N/A
N/A
> chore(events): Remove cocktail night ticket link

- .github/workflows/ci-dev-pr.yml
Enable PR workflow for 2025 branch.
Enable PR workflow for 2025 branch.
N/A
N/A
> chore(ci): Enable PR workflow for 2025 branch

- src/app/(account)/settings/tabs/MembershipSettings.tsx
- src/server/verify-membership-payment.ts
Temporarily pause membership payments during auth migration and check membership expiration correctly.
- Temporarily pause membership payments
- Check if the membership has expired correctly
N/A
N/A
> chore(membership): Temporarily pause membership payments

- package.json
- pnpm-lock.yaml
- src/auth.ts
Use Keycloak realm role instead of client role to determine committee access to only require one role for committee members on Keycloak.
Use Keycloak realm role instead of client role.
N/A
N/A
> chore(auth): Use Keycloak realm role instead of client role

- .env.local.example
- .github/workflows/production.yml
Update .env.local.example and streamline environment variable handling in production workflow.
- Update .env.local.example to include auth and email environment variables
- Refactor production workflow to streamline environment variable handling
N/A
N/A
> chore(ci): Update .env.local.example and streamline env vars in production workflow

- .github/workflows/production.yml
Add database auth token and square credentials to production workflow.
Add database auth token and square credentials to production workflow.
N/A
N/A
> fix(ci): Add database auth token and square credentials for production

- .github/workflows/production.yml
Add secrets to production Docker build.
Add secrets to production Docker build.
N/A
N/A
> fix(ci): Add secrets to production Docker build

- Dockerfile
Use secret mounts for environment variables in build step.
Use secret mounts for environment variables in build step.
N/A
N/A
> fix(Dockerfile): Use secret mounts for environment variables

- .github/workflows/production.yml
Add AUTH_SECRET to production workflow.
Add AUTH_SECRET to production workflow.
N/A
N/A
> fix(ci): Add AUTH_SECRET to production workflow

- .github/workflows/production.yml
- Dockerfile
Remove environment variables and secrets inputs from Dockerfile and workflow.
Remove environment variables and secrets inputs from Dockerfile and workflow.
N/A
N/A
> fix(ci): Remove environment variables and secrets inputs

- .github/workflows/production.yml
Use arm runner for production workflow and remove caching.
Use arm runner for production workflow and remove caching.
N/A
N/A
> chore(ci): Use arm runner for production workflow and remove caching

- .github/workflows/ci-dev-pr.yml
- next-auth.d.ts
- src/app/(account)/join/steps/StepTwo.tsx
- src/app/admin/page.tsx
- src/app/api/payment/route.ts
- src/auth.ts
- src/components/Header/components/Links.tsx
- src/components/Header/index.tsx
- src/server/send-welcome-email.ts
Minor UX improvements and cleanup.
- Correct capitalisation of SMS on join page
- Add sender name to welcome email
- Separate committee and admin roles and add wiki link for committee in user profile menu
- Remove old staging branch from pull request workflow
N/A
N/A
> chore(auth): Minor UX Improvements

- src/data/committee-members.ts
Correct spelling of committee member's name.
Correct spelling of committee member's name.
N/A
N/A
> fix(committee): Correct spelling of committee member's name

- src/app/admin/page.tsx
Increase page size for searching members on the admin page from 50 to 250.
Increase page size for searching members on the admin page from 50 to 250.
N/A
N/A
> chore(admin): Increase page size from 50 to 250

- src/data/events.ts
Update Smash Bros tournament date.
Update Smash Bros tournament date.
N/A
N/A
> chore(event): Update Smash Bros tournament date

- src/app/layout.tsx
- src/components/Notification/BannerNotification.tsx
- src/components/Notification/NotificationContent.tsx
- src/components/Notification/PopupNotification.tsx
- src/components/Notification/index.tsx
- src/components/Notification/types.ts
- src/data/notification.ts
Add notifcation banner and popup.
- Fetch data from cms url + /api/globals/notification
- Parse fields for enabled, notifcation type (banner or popup), notifcation text, notifcation url, url text, left image, and right image
- Make option a full-width banner above the header
- Make option for popup with up to two images support
Fixes #278 
N/A
> feat: Add notification

- src/app/gallery/Gallery.tsx
- src/app/gallery/GalleryControls.tsx
Add year to display name in gallery.
- Add year to display name in gallery
- Update default number of images to 25 and adjust options in GalleryControls
N/A
N/A
> chore(gallery): Add year to display name in gallery

- .env.dev.docker
- .env.local.example
- dev.Dockerfile
- src/app/gallery/GalleryCard.tsx
- src/app/gallery/GalleryOverview.tsx
- src/app/gallery/page.tsx
- src/components/Footer.tsx
Init db on dev Docker, fix footer index & gallery re-render.
- Update dev Dockerfile to include db files and push cmd
- Add Payload CMS environment variable comment to environment example files
- Adjust z-index of footer to allow clicking buttons
- Refactor GalleryOverview with seperate GalleryCard component and fix re-render issue
N/A
N/A
> fix(dev/gallery): Init DB on Dev Docker, Fix Footer Index & Gallery Re-render

- src/data/committee-members.ts
Updated committee members list
Changed name of old committee member with new one
None
None
> chore: Update committee members list
